receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  file/traces:
    path: /tmp/output/traces.json
    format: json
  # file/metrics:
  #   path: /tmp/output/metrics.json
  #   format: json
service:
  pipelines:
    # metrics:
    #   receivers: [otlp]
    #   exporters: [file/metrics]
    traces:
      receivers: [otlp]
      exporters: [file/traces]
